language: 足利両毛弁
author: ゆーちき(https://twitter.com/yuchiki1000yen)
github: https://github.com/yuchiki/taiyaku-kun
introduction: |
  <p>
    このページは、共通語と足利両毛弁の一部音声付き対訳集です。
    対訳作成者は管理者で、音声は管理者による吹き込みです。
    管理者は中央関東～東京の生まれ育ちですが、家族が両毛地域の出身であり、家庭内では両毛弁を聞いて育ってきました。
  </p>
wordsintroduction: |
  <p>
    共通語と足利両毛弁の対訳のリストです。
  </p>
